/**
 * Documentation Generator - Creates INIT.md for AI agents
 * 
 * Generates comprehensive initialization documentation based on project analysis
 */

const fs = require('fs');
const path = require('path');
const { ProjectAnalyzer } = require('./analyzer');
const { StructureGenerator } = require('./structure');

class DocumentationGenerator {
  constructor(projectRoot) {
    this.projectRoot = projectRoot;
    this.analyzer = new ProjectAnalyzer(projectRoot);
  }

  /**
   * Generate INIT.md documentation and directory structure
   */
  async generate() {
    const analysis = this.analyzer.analyze();
    
    // Generate directory structure first
    const structureGen = new StructureGenerator(this.projectRoot, analysis);
    const structureResult = structureGen.generate();
    
    // Generate INIT.md (overwrite if exists)
    const content = this.buildDocumentation(analysis);
    const aiDir = path.join(this.projectRoot, '.ai');
    const initPath = path.join(aiDir, 'INIT.md');
    const initExisted = fs.existsSync(initPath);
    fs.writeFileSync(initPath, content, 'utf8');
    
    return {
      path: initPath,
      analysis,
      structureFiles: structureResult.created || [],
      skippedFiles: structureResult.skipped || [],
      initExisted
    };
  }

  /**
   * Build documentation content
   */
  buildDocumentation(analysis) {
    const sections = [
      this.buildHeader(analysis),
      this.buildProjectOverview(analysis),
      this.buildTechnologyStack(analysis),
      this.buildProjectStructure(analysis),
      this.buildKeyFiles(analysis),
      this.buildDevelopmentWorkflow(analysis),
      this.buildDocumentationStructure(analysis),
      this.buildDocumentationGuidelines(analysis),
      this.buildAIGuidelines(analysis)
    ];

    return sections.join('\n\n');
  }

  /**
   * Build header section
   */
  buildHeader(analysis) {
    const date = new Date().toISOString().split('T')[0];
    return `# Project Initialization Guide

**Last Updated**: ${date}
**Version**: 1.0.0
**Generated by**: AI Contextor

> This document provides essential context for AI assistants working on this project.
> It was automatically generated based on project structure analysis.

---
`;
  }

  /**
   * Build project overview section
   */
  buildProjectOverview(analysis) {
    const typeDescriptions = {
      'frontend': 'Frontend web application',
      'backend': 'Backend API/server application',
      'fullstack': 'Full-stack application (frontend + backend)',
      'library': 'Library or package',
      'monorepo': 'Monorepo workspace',
      'unknown': 'Project type could not be determined'
    };

    const type = analysis.type || 'unknown';
    const description = typeDescriptions[type] || typeDescriptions.unknown;

    let content = `## 📋 Project Overview

**Project Type**: ${type.charAt(0).toUpperCase() + type.slice(1)}
**Description**: ${description}

`;

    if (analysis.languages.length > 0) {
      content += `**Primary Languages**: ${analysis.languages.join(', ')}\n\n`;
    }

    if (analysis.hasGit) {
      content += `**Version Control**: Git\n\n`;
    }

    if (analysis.hasTests) {
      content += `**Testing**: ${analysis.testFrameworks.length > 0 
        ? analysis.testFrameworks.join(', ') 
        : 'Tests detected'}\n\n`;
    }

    return content;
  }

  /**
   * Build technology stack section
   */
  buildTechnologyStack(analysis) {
    let content = `## 🛠️ Technology Stack

`;

    if (analysis.frameworks.length > 0) {
      content += `### Frameworks & Libraries\n`;
      analysis.frameworks.forEach(fw => {
        content += `- **${fw}**\n`;
      });
      content += '\n';
    }

    if (analysis.buildTools.length > 0) {
      content += `### Build Tools\n`;
      analysis.buildTools.forEach(tool => {
        content += `- **${tool}**\n`;
      });
      content += '\n';
    }

    if (analysis.testFrameworks.length > 0) {
      content += `### Testing\n`;
      analysis.testFrameworks.forEach(tool => {
        content += `- **${tool}**\n`;
      });
      content += '\n';
    }

    if (analysis.frameworks.length === 0 && analysis.buildTools.length === 0) {
      content += `*No major frameworks detected. This appears to be a vanilla JavaScript/TypeScript project.*\n\n`;
    }

    return content;
  }

  /**
   * Build project structure section
   */
  buildProjectStructure(analysis) {
    let content = `## 📁 Project Structure

### Key Directories

`;

    if (analysis.keyDirs.length > 0) {
      const dirDescriptions = {
        'src': 'Main source code directory',
        'lib': 'Library code',
        'app': 'Application code (Next.js/Remix style)',
        'pages': 'Page components/routes',
        'components': 'Reusable UI components',
        'views': 'View templates',
        'public': 'Static assets',
        'server': 'Server-side code',
        'api': 'API routes/endpoints',
        'routes': 'Route definitions',
        'controllers': 'Request controllers',
        'models': 'Data models',
        'services': 'Business logic services',
        'utils': 'Utility functions',
        'helpers': 'Helper functions',
        'config': 'Configuration files',
        'tests': 'Test files',
        'test': 'Test files',
        '__tests__': 'Test files',
        'spec': 'Test specifications',
        'e2e': 'End-to-end tests',
        'cypress': 'Cypress tests',
        'dist': 'Build output',
        'build': 'Build output',
        'out': 'Build output',
        'docs': 'Documentation',
        'documentation': 'Documentation'
      };

      analysis.keyDirs.forEach(dir => {
        const desc = dirDescriptions[dir] || 'Project directory';
        content += `- **\`${dir}/\`** - ${desc}\n`;
      });
    } else {
      content += `*No standard directories detected.*\n`;
    }

    content += '\n### Directory Purpose\n\n';
    
    if (analysis.type === 'frontend') {
      content += `This is a frontend project. Key areas:
- **Components** (if present): Reusable UI components
- **Pages/App**: Route-based or app-router based pages
- **Public**: Static assets served directly
- **Utils/Helpers**: Shared utility functions
`;
    } else if (analysis.type === 'backend') {
      content += `This is a backend project. Key areas:
- **API/Routes**: API endpoint definitions
- **Controllers**: Request handling logic
- **Models**: Data models and schemas
- **Services**: Business logic layer
- **Utils/Helpers**: Shared utility functions
`;
    } else if (analysis.type === 'fullstack') {
      content += `This is a full-stack project combining frontend and backend:
- **Client-side**: Frontend code (components, pages, etc.)
- **Server-side**: Backend code (API, routes, controllers, etc.)
- **Shared**: Code shared between frontend and backend
`;
    } else if (analysis.type === 'library') {
      content += `This is a library/package project:
- **Source code**: Main library implementation
- **Tests**: Test files
- **Build output**: Compiled/distributed files
`;
    }

    return content;
  }

  /**
   * Build key files section
   */
  buildKeyFiles(analysis) {
    let content = `## 📄 Key Files

`;

    if (analysis.keyFiles.length > 0) {
      const fileDescriptions = {
        'package.json': 'Project dependencies and scripts',
        'tsconfig.json': 'TypeScript configuration',
        'jsconfig.json': 'JavaScript project configuration',
        'README.md': 'Project documentation',
        'webpack.config.js': 'Webpack build configuration',
        'vite.config.js': 'Vite build configuration',
        'next.config.js': 'Next.js configuration',
        'tailwind.config.js': 'Tailwind CSS configuration',
        'jest.config.js': 'Jest test configuration',
        'vitest.config.js': 'Vitest test configuration',
        '.env': 'Environment variables',
        '.env.example': 'Example environment variables',
        'Dockerfile': 'Docker container configuration',
        'docker-compose.yml': 'Docker Compose configuration'
      };

      analysis.keyFiles.forEach(file => {
        const desc = fileDescriptions[file] || 'Configuration or documentation file';
        content += `- **\`${file}\`** - ${desc}\n`;
      });
    } else {
      content += `*No standard configuration files detected.*\n`;
    }

    return content;
  }

  /**
   * Build development workflow section
   */
  buildDevelopmentWorkflow(analysis) {
    let content = `## 🚀 Development Workflow

### Getting Started

`;

    if (analysis.keyFiles.includes('package.json')) {
      content += `1. **Install dependencies**:
   \`\`\`bash
   npm install
   \`\`\`

`;
    }

    if (analysis.structure.hasDevScript) {
      content += `2. **Start development server**:
   \`\`\`bash
   npm run dev
   \`\`\`
   *or*
   \`\`\`bash
   npm start
   \`\`\`

`;
    }

    if (analysis.structure.hasBuildScript) {
      content += `3. **Build for production**:
   \`\`\`bash
   npm run build
   \`\`\`

`;
    }

    if (analysis.hasTests) {
      content += `4. **Run tests**:
   \`\`\`bash
   npm test
   \`\`\`

`;
    }

    content += `### Code Organization

`;

    if (analysis.type === 'frontend') {
      content += `- Follow component-based architecture
- Keep components in dedicated directories
- Use consistent naming conventions
- Separate concerns (UI, logic, data)
`;
    } else if (analysis.type === 'backend') {
      content += `- Follow MVC or layered architecture
- Keep routes, controllers, and models separate
- Use services for business logic
- Maintain clear API structure
`;
    } else {
      content += `- Follow project-specific conventions
- Maintain clear separation of concerns
- Use consistent naming patterns
`;
    }

    return content;
  }

  /**
   * Build documentation structure section
   */
  buildDocumentationStructure(analysis) {
    const type = analysis.type || 'unknown';
    let structure = '';
    
    if (type === 'frontend') {
      structure = `## 📚 Documentation Structure

This project uses a structured documentation framework in the \`.ai\` directory:

\`\`\`
.ai/
├── INIT.md                      # Project context (this file)
├── architecture/
│   ├── system-overview.md       # Overall system architecture
│   ├── component-architecture.md # Component structure and patterns
│   └── routing.md               # Routing and navigation
├── components/
│   ├── component-guidelines.md  # Component creation guidelines
│   └── ui-patterns.md           # UI patterns and design system
├── state-management/
│   └── state-overview.md        # State management approach
├── api/
│   └── api-integration.md       # API integration patterns
└── styling/
    └── styling-guide.md         # Styling approach and guidelines
\`\`\`

### Documentation Organization

- **architecture/** - High-level system design and architectural decisions
- **components/** - Component patterns, guidelines, and UI patterns
- **state-management/** - State management strategy and patterns
- **api/** - API integration and communication patterns
- **styling/** - Styling approach and design system

Each documentation file follows a consistent structure with metadata, overview, details, and related documentation links.`;
    } else if (type === 'backend') {
      structure = `## 📚 Documentation Structure

This project uses a structured documentation framework in the \`.ai\` directory:

\`\`\`
.ai/
├── INIT.md                      # Project context (this file)
├── architecture/
│   ├── system-overview.md       # Overall system architecture
│   ├── api-design.md            # API design principles
│   └── service-architecture.md  # Service layer architecture
├── database/
│   ├── database-schema.md       # Database schema documentation
│   └── migrations.md            # Migration strategy
├── api/
│   ├── endpoints.md             # API endpoints documentation
│   └── authentication.md        # Authentication and authorization
└── services/
    └── business-logic.md        # Business logic and domain rules
\`\`\`

### Documentation Organization

- **architecture/** - System architecture and design decisions
- **database/** - Database schema and migration documentation
- **api/** - API endpoints and authentication
- **services/** - Business logic and domain rules`;
    } else if (type === 'fullstack') {
      structure = `## 📚 Documentation Structure

This project uses a structured documentation framework in the \`.ai\` directory:

\`\`\`
.ai/
├── INIT.md                      # Project context (this file)
├── architecture/
│   ├── system-overview.md       # Overall system architecture
│   └── client-server.md         # Client-server communication
├── frontend/
│   ├── frontend-overview.md     # Frontend architecture
│   └── components.md           # Frontend components
├── backend/
│   ├── backend-overview.md      # Backend architecture
│   └── api.md                   # Backend API
├── shared/
│   └── shared-code.md           # Shared code between frontend/backend
└── database/
    └── database-schema.md        # Database schema
\`\`\`

### Documentation Organization

- **architecture/** - Full-stack architecture and communication patterns
- **frontend/** - Frontend-specific documentation
- **backend/** - Backend-specific documentation
- **shared/** - Shared code and types
- **database/** - Database schema and design`;
    } else if (type === 'library') {
      structure = `## 📚 Documentation Structure

This project uses a structured documentation framework in the \`.ai\` directory:

\`\`\`
.ai/
├── INIT.md                      # Project context (this file)
├── architecture/
│   ├── system-overview.md       # Library architecture overview
│   └── api-design.md            # API design principles
├── api/
│   ├── public-api.md            # Public API documentation
│   └── internal-api.md          # Internal API (for maintainers)
└── examples/
    └── usage-examples.md         # Usage examples and patterns
\`\`\`

### Documentation Organization

- **architecture/** - Library architecture and design decisions
- **api/** - Public and internal API documentation
- **examples/** - Usage examples and patterns`;
    } else if (type === 'monorepo') {
      structure = `## 📚 Documentation Structure

This project uses a structured documentation framework in the \`.ai\` directory:

\`\`\`
.ai/
├── INIT.md                      # Project context (this file)
├── architecture/
│   ├── monorepo-overview.md     # Monorepo architecture
│   └── workspace-structure.md   # Workspace organization
└── packages/
    └── package-overview.md       # Package documentation
\`\`\`

### Documentation Organization

- **architecture/** - Monorepo architecture and workspace structure
- **packages/** - Individual package documentation`;
    } else {
      structure = `## 📚 Documentation Structure

This project uses a structured documentation framework in the \`.ai\` directory:

\`\`\`
.ai/
├── INIT.md                      # Project context (this file)
├── architecture/
│   └── system-overview.md       # System architecture overview
└── components/
    └── components-overview.md   # Components overview
\`\`\`

### Documentation Organization

- **architecture/** - System architecture and design
- **components/** - Component documentation`;
    }
    
    return structure;
  }

  /**
   * Build documentation guidelines section
   */
  buildDocumentationGuidelines(analysis) {
    return `## 📝 Documentation Guidelines

### File Documentation

When creating or updating documentation files in this \`.ai\` directory:

1. **Always include metadata**:
   - \`**Last Updated**\`: YYYY-MM-DD format
   - \`**Version**\`: Version number or date
   - \`## 🔗 Related Documentation\`: Links to related docs

2. **Structure your documentation**:
   - Clear headings and sections
   - Code examples where relevant
   - Links to related files and documentation
   - Diagrams or visual aids when helpful

3. **Keep documentation fresh**:
   - Update when code changes
   - Review regularly
   - Remove outdated information

### Example Documentation Template

\`\`\`markdown
# Document Title

**Last Updated**: YYYY-MM-DD
**Version**: 1.0.0

## Overview
Brief description of what this document covers.

## Details
Main content here.

## 🔗 Related Documentation
- [Link to related doc](./other-doc.md)
- [Another link](./another-doc.md)
\`\`\`
`;
  }

  /**
   * Build AI-specific guidelines section
   */
  buildAIGuidelines(analysis) {
    let content = `## 🤖 AI Assistant Guidelines

### When Working on This Project

1. **Understand the Context**:
   - Review this INIT.md file first
   - Check related documentation in \`.ai\` directory
   - Understand the project type: **${analysis.type}**

`;

    if (analysis.frameworks.length > 0) {
      content += `2. **Framework Awareness**:
   - This project uses: ${analysis.frameworks.join(', ')}
   - Follow framework-specific best practices
   - Respect framework conventions and patterns

`;
    }

    content += `3. **Code Changes**:
   - Make changes that align with project structure
   - Follow existing code patterns and conventions
   - Update relevant documentation when code changes
   - Consider impact on related files

4. **Documentation Updates**:
   - When modifying code, check if documentation needs updates
   - Update "Last Updated" dates in documentation
   - Add new documentation for new features
   - Remove or update outdated documentation

5. **Testing**:
`;

    if (analysis.hasTests) {
      content += `   - Tests are present: ${analysis.testFrameworks.join(', ') || 'Test framework detected'}
   - Ensure tests pass before suggesting changes
   - Add tests for new features when appropriate

`;
    } else {
      content += `   - No test framework detected
   - Consider adding tests for critical functionality

`;
    }

    content += `6. **Project-Specific Notes**:
`;

    if (analysis.type === 'monorepo') {
      content += `   - This is a monorepo - be aware of workspace structure
   - Changes might affect multiple packages
   - Check workspace dependencies

`;
    }

    if (analysis.buildTools.length > 0) {
      content += `   - Build tool: ${analysis.buildTools.join(', ')}
   - Consider build implications when making changes

`;
    }

    content += `### Common Tasks

- **Adding a new feature**: Update code, add tests, update documentation
- **Fixing a bug**: Fix code, verify tests, update docs if behavior changes
- **Refactoring**: Update all affected files, maintain tests, update documentation
- **Documentation**: Keep it accurate, up-to-date, and well-structured

### Questions to Consider

Before making changes, ask:
1. Does this align with the project's architecture?
2. Are there similar patterns already in the codebase?
3. What documentation needs to be updated?
4. Are there tests that need to be updated or added?
5. What are the dependencies and side effects?

---
`;

    return content;
  }
}

module.exports = { DocumentationGenerator };

